language: python
services:
  - docker

before_install:
  - docker build -t ansible-ci:latest .
  - docker run -d -it --name ansible-ci ansible-ci:latest

jobs:
  include:
    - stage: test
      name: test
      script:
        - ls
